[theme]
# Base: 'dark' para un aspecto moderno, 'light' para un aspecto clásico.
base = "dark" 

# primaryColor: Color principal usado en botones, enlaces y el delta de st.metric.
primaryColor = "#007BFF" 

# backgroundColor: El fondo principal de la aplicación.
backgroundColor = "#0E1117" 

# secondaryBackgroundColor: Color de fondo para la barra lateral (sidebar) y contenedores.
secondaryBackgroundColor = "#262730"

# textColor: Color principal del texto.
textColor = "#00BA41"

#color rojo "#BC2929"


# font: Tipo de fuente.
font = "sans serif"